// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nufngwmekxqxeeqsymjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51Zm5nd21la3hxeGVlcXN5bWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMDU4NDgsImV4cCI6MjA2OTY4MTg0OH0.j2e36lngvF8R9IsIymCG-IZoA_zMD9YSzEuZMcEOeEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});